apiVersion: v1
kind: Service
metadata:
  name: db #this is what the application name it is looking for
  labels:
    name: db-service
    app: voting-app
spec:
  ports:
  - port: 5432
    targetport: 5432
  selector: #this links the service to the redis pod
    name: postgres-pod
    app: voting-app
