apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app
spec:
  ports:
  - port: 6379
    targetport: 6379
  selector: #this links the service to the redis pod
    name: redis-pod
    app: voting-app
