apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    name: worker-service
    app: voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetport: 80
  selector: #this links the service to the redis pod
    name: worker-app-pod
    app: voting-app
